name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Test
        run: make test

      - name: Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: pinceau.zip
          path: dist/pinceau.zip
