name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pinceau.zip
          path: dist/pinceau.zip
